name: CI

on: [push]

jobs:
  Quality:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.x
      - run: pip install flake8
      - run: python -m flake8

  # BuildAndPublishImage:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Build image and push it to DockerHub
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: '.'
  #         file: ./Dockerfile
  #         tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  #         push: true

  #     - name: Image digest
  #       run: echo ${{ steps.docker_build.outputs.digest }}

  # Test:
  #   runs-on: Ubuntu-20.04
  #   container: docker://${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  #   steps:
      # - name: Installs test dependencies
      #   run: pip install pytest
      # - name: Runs tests
      #   run: python -m pytest tests/

  Test:
    runs-on: Ubuntu-20.04

    env:
      IMAGE_NAME: ${{ github.repository }}
      IMAGE_TAG: ${{ github.ref_name }}
      # DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      # DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Install test dependencies
        run: pip install pytest
      
      - name: Run tests
        run: python -m pytest tests
