name: CI

on: [push]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Quality:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python_version: 3.9.x
      - run: pip install flake8
      - run: python -m flake8

  # Tests:
  #   runs:
  #     using: docker
  #     image: Dockerfile
  #     args:
  #       - pythonS
      # - run: sudo apt-get install python3-pip
      # - run: python3 -m pip install --no-cache-dir --upgrade pip
      # - run: python3 -m pip install flake8
      # - run: python3 -m flake8

  # Tests:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-python@v2

  BuildAndPublishImage:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image and push it to DockerHub
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: '.'
          file: ./Dockerfile
          # Note: tags has to be all lower-case
          tags: ${{ env.IMAGE_NAME }}:${{ github.ref_name }} 
          # build on feature branches, push only on main branch
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
